/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as smartContracts from "./smart-contracts";
export type { smartContracts };
export * as factories from "./factories";
export type { Ownable } from "./@openzeppelin/contracts/access/Ownable";
export { Ownable__factory } from "./factories/@openzeppelin/contracts/access/Ownable__factory";
export type { TipJar } from "./smart-contracts/contracts/TipJar";
export { TipJar__factory } from "./factories/smart-contracts/contracts/TipJar__factory";
